name: sole_trader
description: Application to help sole traders and freelancers with quoting, tracking jobs, and invoicing clients

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+4

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  sqflite: ^1.3.1
  path_provider: ^1.6.11
  duration: ^2.0.15
  pdf: ^1.10.0
  flutter_full_pdf_viewer: ^1.0.6
  printing: ^3.5.0
  rflutter_alert: ^1.0.2
  provider: ^4.3.2
  flutter_mailer: ^0.5.1
  file_picker: ^2.0.0
  introduction_screen: ^1.0.7
  shared_preferences: ^0.5.10
  after_layout: ^1.0.7+2
  url_launcher: ^5.4.10
  purchases_flutter: ^1.1.1
  flutter_share: ^1.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/roboto1.ttf
    - assets/fonts/roboto2.ttf
    - assets/fonts/roboto3.ttf
    - assets/images/add-client.gif
    - assets/images/add-job.gif
    - assets/images/generate-invoice.gif
    - assets/images/job-in-progress.gif
    - assets/images/my-details.gif
    - assets/images/sole-trader-logo-transparent.png
    - assets/images/add-quote-button.jpg
    - assets/images/tap-on-quote.jpg
    - assets/images/add-job-button.jpg
    - assets/images/add-job-2-button.jpg
    - assets/images/add-job-3-button.jpg
    - assets/images/generate-quote-button.jpg
    - assets/images/generate-invoice-button.jpg
    - assets/images/my-clients-screen.jpg
    - assets/images/tap-on-clock-in-button.jpg
    - assets/images/choose-client-for-invoice.jpg
    - assets/images/archive-job-slide.jpg
    - assets/images/include-archived-jobs-restore.jpg
    - assets/images/my-clients-screen-settings-tap.jpg
    - assets/images/archive-client.jpg
    - assets/images/archived-clients-button.jpg
    - assets/images/archived-clients-list.jpg
    - assets/images/archived-clients-list-settings-icon-tap.jpg
    - assets/images/restore-archived-client.jpg
    - assets/images/tax-invoice-sample.jpg
    - assets/images/options-top-drop-down-menu.jpg
    - assets/images/duplicate-job-tip.jpg
    - assets/images/reset-job-clock.jpg
    - assets/images/clients-screen-invoice-tap.jpg
    - assets/images/add-as-job-button.jpg
    - assets/images/delete-job-entry-dismissible.jpg
    - assets/images/sole-trader-logo.png
    - assets/images/invoicing-button.png
    - assets/images/plus-new-job-button.png
    - assets/images/options-button.png
    - assets/images/quotes-button.png
    - assets/images/fact_check-icon.png

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins-regular.ttf
        - asset: assets/fonts/poppins-light.ttf
          weight: 300
        - asset: assets/fonts/poppins-medium.ttf
          weight: 500
        - asset: assets/fonts/poppins-regular.ttf
          weight: 600
        - asset: assets/fonts/poppins-bold.ttf
          weight: 700
        - asset: assets/fonts/poppins-extrabold.ttf
          weight: 800
